添加磁盘报警规则
cryptape/cita-monitor pull request #153
Opened 2020-02-20 08:32 UTC by mfuuzy

2020-02-20 13:59 UTC, rainchen requested changes
please rewrite your commit message in English

2020-02-21 02:03 UTC, rainchen commented on server/config/alert.rules
> +    expr: (Node_Get_DiskInfo_UsedSize / ( Node_Get_DiskInfo_UsedSize + Node_Get_DiskInfo_FreeSize)) * 100   > 80
wrong expr, please check https://github.com/citahub/cita-monitor/issues/151
should use `FreeSize percentage`  < 10

2020-02-21 02:22 UTC, mfuuzy commented on server/config/alert.rules
> +    expr: (Node_Get_DiskInfo_UsedSize / ( Node_Get_DiskInfo_UsedSize + Node_Get_DiskInfo_FreeSize)) * 100   > 80
可以了

2020-02-25 08:35 UTC, rainchen commented on server/config/alert.rules
> +      summary: "DISK useage overflow"
磁盘空间没有 overflow 的说法

2020-02-25 08:35 UTC, rainchen requested changes
please update

2020-03-11 09:21 UTC, rainchen commented on server/config/alert.rules
> +  - alert: DISK_Warning
把 `DISK` 改为 `Disk`

2020-03-11 09:25 UTC, rainchen commented on server/config/alert.rules
> +      summary: "DISK useage overflow"
summary 内容改 `Disk is running out of free space`

2020-03-11 09:59 UTC, rainchen approved these changes

2020-03-11 10:01 UTC, rainchen commented
@mfuuzy must change base branch to develop

2020-03-11 10:01 UTC, rainchen requested changes
wrong base branch

2020-03-11 10:08 UTC, rainchen approved these changes

2020-03-11 10:09 UTC, merged